import { test, expect } from '@playwright/test';await page.goto('https://neweudit1-4u7e.vercel.app/login');
await page.getByRole('textbox', { name: 'Email' }).click();
await page.getByRole('textbox', { name: 'Email' }).fill('test@gmail.com');
await page.getByRole('textbox', { name: 'Password' }).click();
await page.getByRole('textbox', { name: 'Password' }).fill('test');
await page.getByRole('button', { name: 'Login' }).click();
await page.locator('div').filter({ hasText: /^StaffManage and View staff information with ease\.show$/ }).getByRole('link').click();
await page.getByRole('button', { name: 'Add Staff' }).click();
await page.getByRole('combobox').filter({ hasText: 'Select your Salutation' }).click();
await page.getByRole('option', { name: 'Mr.' }).click();
await page.getByRole('textbox', { name: 'First Name' }).click();
await page.getByRole('textbox', { name: 'First Name' }).fill('rrhuu');
await page.getByRole('textbox', { name: 'Last Name' }).click();
await page.getByRole('textbox', { name: 'Last Name' }).fill('jjj');
await page.getByRole('textbox', { name: 'Email' }).click();
await page.getByRole('textbox', { name: 'Email' }).fill('jjj@gmail.com');
await page.getByRole('textbox', { name: 'Please enter at least 10' }).click();
await page.getByRole('textbox', { name: 'Please enter at least 10' }).fill('1236547894');
await page.getByRole('textbox', { name: 'Enter your id' }).click();
await page.getByRole('textbox', { name: 'Enter your id' }).fill('hh');
await page.getByPlaceholder('DD/MM/YYYY').fill('1993-11-11');
await page.getByRole('combobox').filter({ hasText: 'Select your languages' }).click();
await page.getByLabel('English').getByText('English').click();
await page.getByRole('combobox').filter({ hasText: 'Select your gender' }).click();
await page.getByRole('option', { name: 'Male', exact: true }).click();
await page.getByRole('combobox').filter({ hasText: 'Select your Role' }).click();
await page.getByLabel('Staff').getByText('Staff').click();
await page.getByRole('button', { name: 'Save' }).click();
await page.locator('div:nth-child(12) > .mt-10 > .inline-flex').click();
await page.locator('div').filter({ hasText: /^Employee ID$/ }).click();
await page.getByRole('button', { name: 'Save' }).click();

test('test1', async ({ page }) => {
  await page.goto('https://neweudit1-4u7e.vercel.app/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('test');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: /^StaffManage and View staff information with ease\.show$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Staff' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select your Salutation' }).click();
  await page.getByRole('option', { name: 'Mrs.' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('rohini');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('s');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('rohinir@gmail.com');
  await page.getByRole('textbox', { name: 'Please enter at least 10' }).click();
  await page.getByRole('textbox', { name: 'Please enter at least 10' }).fill('7736067508');
  await page.getByRole('textbox', { name: 'Enter your id' }).click();
  await page.getByRole('textbox', { name: 'Enter your id' }).fill('11');
  await page.getByPlaceholder('DD/MM/YYYY').fill('1999-11-11');
  await page.getByRole('combobox').filter({ hasText: 'Select your languages' }).click();
  await page.getByLabel('English').getByText('English').click();
  await page.getByRole('combobox').filter({ hasText: 'Select your gender' }).click();
  await page.getByLabel('Female').getByText('Female').click();
  await page.getByRole('button', { name: 'Save' }).click();
});